FROM python:3.11-slim

WORKDIR /app

# 1. 手动安装 Playwright 所需的系统库
# 注意：这里将报错的 ttf-unifont 替换为了 fonts-unifont
RUN apt-get update && apt-get install -y --no-install-recommends \
    libnss3 \
    libnspr4 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libxkbcommon0 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libgbm1 \
    libasound2 \
    fonts-liberation \
    fonts-unifont \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir --root-user-action=ignore -r requirements.txt

# 2. 只安装浏览器内核，不再尝试安装系统依赖
RUN playwright install chromium

COPY . .

EXPOSE 8000

CMD ["python", "main.py"]
